# **machine learning based Instagram Marketing Strategy**

Data Collection

## Web Scraping Data Collection - Yahoo Finance

In [ ]:
import numpy as np
import requests
import pandas as pd
np.random.seed(42)

In [ ]:
# Data URL
url = "https://query1.finance.yahoo.com/v1/finance/screener/predefined/saved"

# Web Scrapping Parameters
params = {
    "scrIds": "most_expensive_stocks",
    "count": 100,
    "start": 0
}

headers = {
    "User-Agent": "Mozilla/5.0"
}

In [ ]:
# Data Extraction from URL
all_rows = []
start = 0
count = 100

# Looping over stocks
while True:
    params["start"] = start
    response = requests.get(url, params=params, headers=headers).json()
    quotes = response["finance"]["result"][0]["quotes"]

    if not quotes:
        break

    all_rows.extend(quotes)
    start += count

In [ ]:
# Overview of Data
all_rows[1]

{'language': 'en-US',
 'region': 'US',
 'quoteType': 'EQUITY',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'currency': 'USD',
 'bid': 6400.0,
 'ask': 6590.0,
 'marketCap': 18159245312,
 'exchange': 'NYQ',
 'fiftyTwoWeekHigh': 8618.28,
 'fiftyTwoWeekLow': 6301.03,
 'financialCurrency': 'USD',
 'regularMarketChangePercent': -0.471003,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 490887000000,
 'priceHint': 2,
 'postMarketChangePercent': 0.77031326,
 'postMarketTime': 1774390561,
 'postMarketPrice': 6550.0,
 'postMarketChange': 50.069824,
 'regularMarketChange': -30.7598,
 'regularMarketTime': 1774382616,
 'regularMarketPrice': 6499.93,
 'regularMarketDayHigh': 6542.15,
 'regularMarketDayRange': '6453.84 - 6542.15',
 'regularMarketDayLow': 6453.84,
 'regularMarketVolume': 15821,
 'regularMarketPreviousClose': 6530.69,
 'bidSize': 20,
 'askSize': 10,
 'market': 'us_market',
 'messageBoardId': 'finmb_182505',
 'fullExchangeName': 'NYSE',
 'longName': 'NVR, Inc.',
 'regularMarketOpen': 6480.0,
 'averageDailyVolume3Month': 28178,
 'averageDailyVolume10Day': 29640,
 'corporateActions': [],
 'fiftyTwoWeekLowChange': 198.90039,
 'fiftyTwoWeekLowChangePercent': 0.03156633,
 'fiftyTwoWeekRange': '6301.03 - 8618.28',
 'fiftyTwoWeekHighChange': -2118.35,
 'fiftyTwoWeekHighChangePercent': -0.2457973,
 'fiftyTwoWeekChangePercent': -11.141473,
 'earningsTimestamp': 1769607000,
 'earningsTimestampStart': 1776774600,
 'earningsTimestampEnd': 1776774600,
 'isEarningsDateEstimate': True,
 'trailingAnnualDividendRate': 0.0,
 'trailingPE': 14.969898,
 'trailingAnnualDividendYield': 0.0,
 'marketState': 'POSTPOST',
 'epsTrailingTwelveMonths': 434.2,
 'epsForward': 451.5652,
 'epsCurrentYear': 396.89844,
 'priceEpsCurrentYear': 16.37681,
 'sharesOutstanding': 2778119,
 'bookValue': 1380.613,
 'fiftyDayAverage': 7360.245,
 'fiftyDayAverageChange': -860.31494,
 'fiftyDayAverageChangePercent': -0.11688673,
 'twoHundredDayAverage': 7575.147,
 'twoHundredDayAverageChange': -1075.2168,
 'twoHundredDayAverageChangePercent': -0.14194006,
 'forwardPE': 14.394223,
 'priceToBook': 4.708003,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'esgPopulated': False,
 'tradeable': False,
 'cryptoTradeable': False,
 'shortName': 'NVR, Inc.',
 'displayName': 'NVR',
 'symbol': 'NVR'}

In [ ]:
# Converting data to pandas
data_yf = pd.DataFrame(all_rows)
data_yf.head()

,language,region,quoteType,typeDisp,quoteSourceName,triggerable,customPriceAlertConfidence,currency,bid,ask,...,tickerChangeDate,prevExchange,exchangeTransferDate,netAssets,netExpenseRatio,ytdReturn,trailingThreeMonthReturns,trailingThreeMonthNavReturns,newListingDate,openInterest
0,en-US,US,EQUITY,Equity,Delayed Quote,False,LOW,USD,719106.94,723295.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,en-US,US,EQUITY,Equity,Delayed Quote,False,LOW,USD,6400.00,6590.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,en-US,US,EQUITY,Equity,Delayed Quote,False,LOW,USD,5204.96,5226.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,en-US,US,EQUITY,Equity,Nasdaq Real Time Price,True,HIGH,USD,4290.28,4398.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,en-US,US,EQUITY,Equity,Nasdaq Real Time Price,False,LOW,USD,3348.62,3450.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Data Structure
data_yf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7595 entries, 0 to 7594
Data columns (total 100 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   language                           7595 non-null   object
 1   region                             7595 non-null   object
 2   quoteType                          7595 non-null   object
 3   typeDisp                           7595 non-null   object
 4   quoteSourceName                    6725 non-null   object
 5   triggerable                        7595 non-null   bool
 6   customPriceAlertConfidence         7595 non-null   object
 7   currency                           7587 non-null   object
 8   bid                                7404 non-null   float64
 9   ask                                7407 non-null   float64
 10  marketCap                          6103 non-null   float64
 11  exchange                           7595 non-null   object
 12  fiftyTwoWeekHigh                   7518 non-null   float64
 13  fiftyTwoWeekLow                    7518 non-null   float64
 14  financialCurrency                  6663 non-null   object
 15  regularMarketChangePercent         7562 non-null   float64
 16  hasPrePostMarketData               7595 non-null   bool
 17  firstTradeDateMilliseconds         7300 non-null   float64
 18  priceHint                          7595 non-null   int64
 19  postMarketChangePercent            6325 non-null   float64
 20  postMarketTime                     6325 non-null   float64
 21  postMarketPrice                    6325 non-null   float64
 22  postMarketChange                   6325 non-null   float64
 23  regularMarketChange                7595 non-null   float64
 24  regularMarketTime                  7595 non-null   int64
 25  regularMarketPrice                 7595 non-null   float64
 26  regularMarketDayHigh               7518 non-null   float64
 27  regularMarketDayRange              7518 non-null   object
 28  regularMarketDayLow                7518 non-null   float64
 29  regularMarketVolume                7518 non-null   float64
 30  regularMarketPreviousClose         7595 non-null   float64
 31  bidSize                            7402 non-null   float64
 32  askSize                            7404 non-null   float64
 33  market                             7595 non-null   object
 34  messageBoardId                     7449 non-null   object
 35  fullExchangeName                   7595 non-null   object
 36  longName                           7294 non-null   object
 37  regularMarketOpen                  7510 non-null   float64
 38  averageDailyVolume3Month           7028 non-null   float64
 39  averageDailyVolume10Day            7028 non-null   float64
 40  corporateActions                   7595 non-null   object
 41  fiftyTwoWeekLowChange              7518 non-null   float64
 42  fiftyTwoWeekLowChangePercent       7518 non-null   float64
 43  fiftyTwoWeekRange                  7518 non-null   object
 44  fiftyTwoWeekHighChange             7518 non-null   float64
 45  fiftyTwoWeekHighChangePercent      7518 non-null   float64
 46  fiftyTwoWeekChangePercent          7028 non-null   float64
 47  earningsTimestamp                  3902 non-null   float64
 48  earningsTimestampStart             5565 non-null   float64
 49  earningsTimestampEnd               5565 non-null   float64
 50  isEarningsDateEstimate             5506 non-null   object
 51  trailingAnnualDividendRate         7230 non-null   float64
 52  trailingPE                         3621 non-null   float64
 53  trailingAnnualDividendYield        7225 non-null   float64
 54  marketState                        7595 non-null   object
 55  epsTrailingTwelveMonths            6268 non-null   float64
 56  epsForward                         4483 non-null   float64
 57  epsCurrentYear                     3837 non-null   float64
 58  priceEpsCurrentYear                3832 non-null   float64
 59  sharesOutstanding                  6102 non-null   float64
 60  bookValue                          6853 non-null   float64
 61  fiftyDayAverage                    7028 non-null   float64
 62  fiftyDayAverageChange              7028 non-null   float64
 63  fiftyDayAverageChangePercent       7028 non-null   float64
 64  twoHundredDayAverage               7028 non-null   float64
 65  twoHundredDayAverageChange         7028 non-null   float64
 66  twoHundredDayAverageChangePercent  7028 non-null   float64
 67  forwardPE                          4470 non-null   float64
 68  priceToBook                        6845 non-null   float64
 69  sourceInterval                     7595 non-null   int64
 70  exchangeDataDelayedBy              7595 non-null   int64
 71  exchangeTimezoneName               7595 non-null   object
 72  exchangeTimezoneShortName          7595 non-null   object
 73  gmtOffSetMilliseconds              7595 non-null   int64
 74  esgPopulated                       7595 non-null   bool
 75  tradeable                          7595 non-null   bool
 76  cryptoTradeable                    7595 non-null   bool
 77  shortName                          7397 non-null   object
 78  displayName                        5826 non-null   object
 79  symbol                             7595 non-null   object
 80  dividendYield                      2761 non-null   float64
 81  dividendDate                       3617 non-null   float64
 82  dividendRate                       2759 non-null   float64
 83  averageAnalystRating               2738 non-null   object
 84  earningsCallTimestampStart         4220 non-null   float64
 85  earningsCallTimestampEnd           4220 non-null   float64
 86  prevName                           1154 non-null   object
 87  nameChangeDate                     1154 non-null   object
 88  ipoExpectedDate                    1851 non-null   object
 89  prevTicker                         1 non-null      object
 90  tickerChangeDate                   1 non-null      object
 91  prevExchange                       1 non-null      object
 92  exchangeTransferDate               1 non-null      object
 93  netAssets                          9 non-null      float64
 94  netExpenseRatio                    18 non-null     float64
 95  ytdReturn                          8 non-null      float64
 96  trailingThreeMonthReturns          8 non-null      float64
 97  trailingThreeMonthNavReturns       8 non-null      float64
 98  newListingDate                     6 non-null      object
 99  openInterest                       1 non-null      float64
dtypes: bool(5), float64(58), int64(5), object(32)
memory usage: 5.5+ MB

In [ ]:
# Saving data
# data_yf.to_csv("data_yf.csv", index=False)

## API Data Access: Alpha Vantage Data API

In [ ]:
# Setting up Alpha Vantage API Access
import requests
import time
API_KEY = "8R3W0JIY5RN5S767"

In [ ]:
# Sample Data Extraction
url = f"https://www.alphavantage.co/query?function=OVERVIEW&symbol=AAPL&apikey={API_KEY}"

response = requests.get(url)

print("Status:", response.status_code)
print("Response:", response.text)

Status: 200
Response: {
    "Information": "We have detected your API key as 8R3W0JIY5RN5S767 and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits."
}

In [ ]:
import requests
import time
from tqdm import tqdm

# Getting Symbols
symbols = data_yf.symbol.tolist()[0:4]

# Storage
results = []

# Loop with progress bar
for sym in tqdm(symbols, desc="Fetching sectors"):
    url = f"https://www.alphavantage.co/query?function=OVERVIEW&symbol={sym}&apikey={API_KEY}"

    response = requests.get(url)
    data = response.json()

    results.append({
        "symbol": sym,
        "sector": data.get("Sector"),
        "industry": data.get("Industry")
    })

    time.sleep(12)

Fetching sectors: 100%|██████████| 4/4 [00:48<00:00, 12.09s/it]

In [ ]:
# API Loop check
results

[{'symbol': 'BRK-A', 'sector': None, 'industry': None},
 {'symbol': 'NVR', 'sector': None, 'industry': None},
 {'symbol': 'SEB', 'sector': None, 'industry': None},
 {'symbol': 'BKNG', 'sector': None, 'industry': None}]

## Web Scraping Data Collection through yFinance Python Package

In [ ]:
import yfinance as yf
import pandas as pd
from tqdm import tqdm

# Converting symbols to list and taking first 1300 due to rate limit
symbols = data_yf.symbol.tolist()[0:1299]

# Setting up storage
results = []

# Loop over symbols
for sym in tqdm(symbols, desc="sectors"):
    try:
        ticker = yf.Ticker(sym)
        info = ticker.info

        sector = info.get("sector")
        industry = info.get("industry")

        results.append({
            "symbol": sym,
            "sector": sector,
            "industry": industry
        })
    except Exception as e:
        print(f"Error fetching {sym}: {e}")
        results.append({
            "symbol": sym,
            "sector": None,
            "industry": None
        })

# Converting results to DataFrame
sector_industry_yf = pd.DataFrame(results)

sectors:  72%|███████▏  | 939/1299 [01:15<00:16, 22.20it/s]

Error fetching HSIC: Too Many Requests. Rate limited. Try after a while.
Error fetching AIG: Too Many Requests. Rate limited. Try after a while.
Error fetching LNTH: Too Many Requests. Rate limited. Try after a while.
Error fetching ENLT: Too Many Requests. Rate limited. Try after a while.
Error fetching ALC: Too Many Requests. Rate limited. Try after a while.
Error fetching SNEX: Too Many Requests. Rate limited. Try after a while.
Error fetching BLLN: Too Many Requests. Rate limited. Try after a while.
Error fetching MNST: Too Many Requests. Rate limited. Try after a while.

sectors:  73%|███████▎  | 947/1299 [01:15<00:12, 28.51it/s]

Error fetching ANIP: Too Many Requests. Rate limited. Try after a while.
Error fetching UNM: Too Many Requests. Rate limited. Try after a while.
Error fetching BC: Too Many Requests. Rate limited. Try after a while.
Error fetching TAYD: Too Many Requests. Rate limited. Try after a while.
Error fetching KSPI: Too Many Requests. Rate limited. Try after a while.
Error fetching STRK: Too Many Requests. Rate limited. Try after a while.
Error fetching WMB: Too Many Requests. Rate limited. Try after a while.
Error fetching AWR: Too Many Requests. Rate limited. Try after a while.

sectors:  74%|███████▎  | 955/1299 [01:15<00:10, 32.05it/s]

Error fetching BCC: Too Many Requests. Rate limited. Try after a while.
Error fetching SFBS: Too Many Requests. Rate limited. Try after a while.
Error fetching BOH: Too Many Requests. Rate limited. Try after a while.
Error fetching SAFT: Too Many Requests. Rate limited. Try after a while.
Error fetching CFFI: Too Many Requests. Rate limited. Try after a while.
Error fetching TNK: Too Many Requests. Rate limited. Try after a while.
Error fetching NKTR: Too Many Requests. Rate limited. Try after a while.
Error fetching SYNA: Too Many Requests. Rate limited. Try after a while.

sectors:  74%|███████▍  | 963/1299 [01:16<00:10, 33.46it/s]

Error fetching RNA: Too Many Requests. Rate limited. Try after a while.
Error fetching CVS: Too Many Requests. Rate limited. Try after a while.
Error fetching STRD: Too Many Requests. Rate limited. Try after a while.
Error fetching TRNS: Too Many Requests. Rate limited. Try after a while.
Error fetching LPX: Too Many Requests. Rate limited. Try after a while.
Error fetching SPB: Too Many Requests. Rate limited. Try after a while.
Error fetching DEO: Too Many Requests. Rate limited. Try after a while.
Error fetching NCSM: Too Many Requests. Rate limited. Try after a while.

sectors:  75%|███████▍  | 971/1299 [01:16<00:09, 34.57it/s]

Error fetching MNDY: Too Many Requests. Rate limited. Try after a while.
Error fetching LB: Too Many Requests. Rate limited. Try after a while.
Error fetching DIOD: Too Many Requests. Rate limited. Try after a while.
Error fetching DRUG: Too Many Requests. Rate limited. Try after a while.
Error fetching SF: Too Many Requests. Rate limited. Try after a while.
Error fetching SOLS: Too Many Requests. Rate limited. Try after a while.
Error fetching CMPR: Too Many Requests. Rate limited. Try after a while.
Error fetching SEZL: Too Many Requests. Rate limited. Try after a while.

sectors:  75%|███████▌  | 979/1299 [01:16<00:09, 35.12it/s]

Error fetching ELF: Too Many Requests. Rate limited. Try after a while.
Error fetching GIB: Too Many Requests. Rate limited. Try after a while.
Error fetching KR: Too Many Requests. Rate limited. Try after a while.
Error fetching VIK: Too Many Requests. Rate limited. Try after a while.
Error fetching GFF: Too Many Requests. Rate limited. Try after a while.
Error fetching SWK: Too Many Requests. Rate limited. Try after a while.
Error fetching LASR: Too Many Requests. Rate limited. Try after a while.
Error fetching AGYS: Too Many Requests. Rate limited. Try after a while.

sectors:  76%|███████▌  | 987/1299 [01:16<00:08, 36.11it/s]

Error fetching LYB: Too Many Requests. Rate limited. Try after a while.
Error fetching SSNC: Too Many Requests. Rate limited. Try after a while.
Error fetching CIB: Too Many Requests. Rate limited. Try after a while.
Error fetching ALB-PA: Too Many Requests. Rate limited. Try after a while.
Error fetching APTV: Too Many Requests. Rate limited. Try after a while.
Error fetching GPN: Too Many Requests. Rate limited. Try after a while.
Error fetching DSGX: Too Many Requests. Rate limited. Try after a while.
Error fetching GEHC: Too Many Requests. Rate limited. Try after a while.

sectors:  77%|███████▋  | 995/1299 [01:16<00:08, 36.49it/s]

Error fetching CBT: Too Many Requests. Rate limited. Try after a while.
Error fetching TNL: Too Many Requests. Rate limited. Try after a while.
Error fetching STNG: Too Many Requests. Rate limited. Try after a while.
Error fetching EIX: Too Many Requests. Rate limited. Try after a while.
Error fetching VAC: Too Many Requests. Rate limited. Try after a while.
Error fetching BMA: Too Many Requests. Rate limited. Try after a while.
Error fetching COO: Too Many Requests. Rate limited. Try after a while.
Error fetching ECPG: Too Many Requests. Rate limited. Try after a while.

sectors:  77%|███████▋  | 1003/1299 [01:17<00:08, 36.73it/s]

Error fetching FTI: Too Many Requests. Rate limited. Try after a while.
Error fetching INSW: Too Many Requests. Rate limited. Try after a while.
Error fetching KTB: Too Many Requests. Rate limited. Try after a while.
Error fetching WAL: Too Many Requests. Rate limited. Try after a while.
Error fetching IONS: Too Many Requests. Rate limited. Try after a while.
Error fetching LNT: Too Many Requests. Rate limited. Try after a while.
Error fetching SUNB: Too Many Requests. Rate limited. Try after a while.
Error fetching BBIO: Too Many Requests. Rate limited. Try after a while.

sectors:  78%|███████▊  | 1011/1299 [01:17<00:07, 36.93it/s]

Error fetching NGVT: Too Many Requests. Rate limited. Try after a while.
Error fetching WBS: Too Many Requests. Rate limited. Try after a while.
Error fetching RBCAA: Too Many Requests. Rate limited. Try after a while.
Error fetching BNS: Too Many Requests. Rate limited. Try after a while.
Error fetching MET: Too Many Requests. Rate limited. Try after a while.
Error fetching HOOD: Too Many Requests. Rate limited. Try after a while.
Error fetching ICFI: Too Many Requests. Rate limited. Try after a while.
Error fetching BHP: Too Many Requests. Rate limited. Try after a while.

sectors:  78%|███████▊  | 1019/1299 [01:17<00:07, 36.94it/s]

Error fetching WGS: Too Many Requests. Rate limited. Try after a while.
Error fetching TRU: Too Many Requests. Rate limited. Try after a while.
Error fetching CTA-PB: Too Many Requests. Rate limited. Try after a while.
Error fetching VVX: Too Many Requests. Rate limited. Try after a while.
Error fetching CQP: Too Many Requests. Rate limited. Try after a while.
Error fetching MMS: Too Many Requests. Rate limited. Try after a while.
Error fetching AXTI: Too Many Requests. Rate limited. Try after a while.
Error fetching NMM: Too Many Requests. Rate limited. Try after a while.

sectors:  79%|███████▉  | 1027/1299 [01:17<00:07, 36.80it/s]

Error fetching BKH: Too Many Requests. Rate limited. Try after a while.
Error fetching TEAM: Too Many Requests. Rate limited. Try after a while.
Error fetching BSX: Too Many Requests. Rate limited. Try after a while.
Error fetching VOYA: Too Many Requests. Rate limited. Try after a while.
Error fetching MMSI: Too Many Requests. Rate limited. Try after a while.
Error fetching SRCE: Too Many Requests. Rate limited. Try after a while.
Error fetching BUD: Too Many Requests. Rate limited. Try after a while.
Error fetching KLIC: Too Many Requests. Rate limited. Try after a while.

sectors:  80%|███████▉  | 1035/1299 [01:18<00:07, 36.98it/s]

Error fetching EMN: Too Many Requests. Rate limited. Try after a while.
Error fetching RKLB: Too Many Requests. Rate limited. Try after a while.
Error fetching ADM: Too Many Requests. Rate limited. Try after a while.
Error fetching IFF: Too Many Requests. Rate limited. Try after a while.
Error fetching IOSP: Too Many Requests. Rate limited. Try after a while.
Error fetching VIST: Too Many Requests. Rate limited. Try after a while.
Error fetching IBKR: Too Many Requests. Rate limited. Try after a while.
Error fetching EEFT: Too Many Requests. Rate limited. Try after a while.

sectors:  80%|████████  | 1043/1299 [01:18<00:06, 36.92it/s]

Error fetching ANDE: Too Many Requests. Rate limited. Try after a while.
Error fetching IBOC: Too Many Requests. Rate limited. Try after a while.
Error fetching HLIO: Too Many Requests. Rate limited. Try after a while.
Error fetching VCTR: Too Many Requests. Rate limited. Try after a while.
Error fetching ES: Too Many Requests. Rate limited. Try after a while.
Error fetching TNC: Too Many Requests. Rate limited. Try after a while.
Error fetching CUBI: Too Many Requests. Rate limited. Try after a while.
Error fetching WPC: Too Many Requests. Rate limited. Try after a while.

sectors:  81%|████████  | 1051/1299 [01:18<00:06, 37.04it/s]

Error fetching NVEC: Too Many Requests. Rate limited. Try after a while.
Error fetching TTAN: Too Many Requests. Rate limited. Try after a while.
Error fetching WMK: Too Many Requests. Rate limited. Try after a while.
Error fetching HL-PB: Too Many Requests. Rate limited. Try after a while.
Error fetching LMND: Too Many Requests. Rate limited. Try after a while.
Error fetching TRMB: Too Many Requests. Rate limited. Try after a while.
Error fetching DAL: Too Many Requests. Rate limited. Try after a while.
Error fetching RUSHA: Too Many Requests. Rate limited. Try after a while.

sectors:  82%|████████▏ | 1059/1299 [01:18<00:06, 36.54it/s]

Error fetching SYF: Too Many Requests. Rate limited. Try after a while.
Error fetching BRO: Too Many Requests. Rate limited. Try after a while.
Error fetching WF: Too Many Requests. Rate limited. Try after a while.
Error fetching PTCT: Too Many Requests. Rate limited. Try after a while.
Error fetching PB: Too Many Requests. Rate limited. Try after a while.
Error fetching PVH: Too Many Requests. Rate limited. Try after a while.
Error fetching GEF: Too Many Requests. Rate limited. Try after a while.
Error fetching ESEA: Too Many Requests. Rate limited. Try after a while.

sectors:  82%|████████▏ | 1067/1299 [01:18<00:06, 36.09it/s]

Error fetching SLGL: Too Many Requests. Rate limited. Try after a while.
Error fetching ATRO: Too Many Requests. Rate limited. Try after a while.
Error fetching TWN: Too Many Requests. Rate limited. Try after a while.
Error fetching NSIT: Too Many Requests. Rate limited. Try after a while.
Error fetching MTX: Too Many Requests. Rate limited. Try after a while.
Error fetching DXCM: Too Many Requests. Rate limited. Try after a while.
Error fetching PHIN: Too Many Requests. Rate limited. Try after a while.
Error fetching SOLV: Too Many Requests. Rate limited. Try after a while.

sectors:  83%|████████▎ | 1075/1299 [01:19<00:06, 36.08it/s]

Error fetching SMG: Too Many Requests. Rate limited. Try after a while.
Error fetching MCHP: Too Many Requests. Rate limited. Try after a while.
Error fetching WRB: Too Many Requests. Rate limited. Try after a while.
Error fetching AUGO: Too Many Requests. Rate limited. Try after a while.
Error fetching EXPO: Too Many Requests. Rate limited. Try after a while.
Error fetching UCTT: Too Many Requests. Rate limited. Try after a while.
Error fetching EQT: Too Many Requests. Rate limited. Try after a while.
Error fetching NWE: Too Many Requests. Rate limited. Try after a while.

sectors:  83%|████████▎ | 1083/1299 [01:19<00:05, 36.56it/s]

Error fetching DOX: Too Many Requests. Rate limited. Try after a while.
Error fetching AOS: Too Many Requests. Rate limited. Try after a while.
Error fetching ALNT: Too Many Requests. Rate limited. Try after a while.
Error fetching FLEX: Too Many Requests. Rate limited. Try after a while.
Error fetching CGON: Too Many Requests. Rate limited. Try after a while.
Error fetching SUN: Too Many Requests. Rate limited. Try after a while.
Error fetching DOO: Too Many Requests. Rate limited. Try after a while.
Error fetching AL: Too Many Requests. Rate limited. Try after a while.

sectors:  84%|████████▍ | 1091/1299 [01:19<00:05, 36.80it/s]

Error fetching HPE-PC: Too Many Requests. Rate limited. Try after a while.
Error fetching FRPT: Too Many Requests. Rate limited. Try after a while.
Error fetching INBX: Too Many Requests. Rate limited. Try after a while.
Error fetching PSTG: Too Many Requests. Rate limited. Try after a while.
Error fetching SYBT: Too Many Requests. Rate limited. Try after a while.
Error fetching MO: Too Many Requests. Rate limited. Try after a while.
Error fetching SPRB: Too Many Requests. Rate limited. Try after a while.
Error fetching TARS: Too Many Requests. Rate limited. Try after a while.

sectors:  85%|████████▍ | 1099/1299 [01:19<00:05, 36.88it/s]

Error fetching SU: Too Many Requests. Rate limited. Try after a while.
Error fetching WSFS: Too Many Requests. Rate limited. Try after a while.
Error fetching BBY: Too Many Requests. Rate limited. Try after a while.
Error fetching HHH: Too Many Requests. Rate limited. Try after a while.
Error fetching TRP: Too Many Requests. Rate limited. Try after a while.
Error fetching MPTI: Too Many Requests. Rate limited. Try after a while.
Error fetching CRC: Too Many Requests. Rate limited. Try after a while.
Error fetching CMC: Too Many Requests. Rate limited. Try after a while.

sectors:  85%|████████▌ | 1107/1299 [01:20<00:05, 36.59it/s]

Error fetching UTMD: Too Many Requests. Rate limited. Try after a while.
Error fetching BA-PA: Too Many Requests. Rate limited. Try after a while.
Error fetching CNS: Too Many Requests. Rate limited. Try after a while.
Error fetching MANE: Too Many Requests. Rate limited. Try after a while.
Error fetching HWC: Too Many Requests. Rate limited. Try after a while.
Error fetching LIVN: Too Many Requests. Rate limited. Try after a while.
Error fetching SMBC: Too Many Requests. Rate limited. Try after a while.
Error fetching GRBK: Too Many Requests. Rate limited. Try after a while.

sectors:  86%|████████▌ | 1115/1299 [01:20<00:04, 36.90it/s]

Error fetching RUSHB: Too Many Requests. Rate limited. Try after a while.
Error fetching SLF: Too Many Requests. Rate limited. Try after a while.
Error fetching ELS: Too Many Requests. Rate limited. Try after a while.
Error fetching FER: Too Many Requests. Rate limited. Try after a while.
Error fetching SAH: Too Many Requests. Rate limited. Try after a while.
Error fetching ANAB: Too Many Requests. Rate limited. Try after a while.
Error fetching KFY: Too Many Requests. Rate limited. Try after a while.
Error fetching GRVY: Too Many Requests. Rate limited. Try after a while.

sectors:  86%|████████▋ | 1123/1299 [01:20<00:04, 37.10it/s]

Error fetching GSBC: Too Many Requests. Rate limited. Try after a while.
Error fetching BKR: Too Many Requests. Rate limited. Try after a while.
Error fetching ODC: Too Many Requests. Rate limited. Try after a while.
Error fetching GRC: Too Many Requests. Rate limited. Try after a while.
Error fetching THFF: Too Many Requests. Rate limited. Try after a while.
Error fetching WFG: Too Many Requests. Rate limited. Try after a while.
Error fetching ON: Too Many Requests. Rate limited. Try after a while.
Error fetching CCZ: Too Many Requests. Rate limited. Try after a while.

sectors:  87%|████████▋ | 1131/1299 [01:20<00:04, 36.78it/s]

Error fetching CECO: Too Many Requests. Rate limited. Try after a while.
Error fetching HALO: Too Many Requests. Rate limited. Try after a while.
Error fetching PBH: Too Many Requests. Rate limited. Try after a while.
Error fetching SUNC: Too Many Requests. Rate limited. Try after a while.
Error fetching RDNT: Too Many Requests. Rate limited. Try after a while.
Error fetching BHRB: Too Many Requests. Rate limited. Try after a while.
Error fetching JOE: Too Many Requests. Rate limited. Try after a while.
Error fetching URBN: Too Many Requests. Rate limited. Try after a while.

sectors:  88%|████████▊ | 1139/1299 [01:20<00:04, 36.75it/s]

Error fetching DINO: Too Many Requests. Rate limited. Try after a while.
Error fetching HBCP: Too Many Requests. Rate limited. Try after a while.
Error fetching WK: Too Many Requests. Rate limited. Try after a while.
Error fetching OXY: Too Many Requests. Rate limited. Try after a while.
Error fetching SHG: Too Many Requests. Rate limited. Try after a while.
Error fetching GSAT: Too Many Requests. Rate limited. Try after a while.
Error fetching UL: Too Many Requests. Rate limited. Try after a while.
Error fetching TRNO: Too Many Requests. Rate limited. Try after a while.

sectors:  88%|████████▊ | 1147/1299 [01:21<00:04, 36.63it/s]

Error fetching NEN: Too Many Requests. Rate limited. Try after a while.
Error fetching SEI: Too Many Requests. Rate limited. Try after a while.
Error fetching MTH: Too Many Requests. Rate limited. Try after a while.
Error fetching MTDR: Too Many Requests. Rate limited. Try after a while.
Error fetching TSN: Too Many Requests. Rate limited. Try after a while.
Error fetching CE: Too Many Requests. Rate limited. Try after a while.
Error fetching CZFS: Too Many Requests. Rate limited. Try after a while.
Error fetching TEX: Too Many Requests. Rate limited. Try after a while.

sectors:  89%|████████▉ | 1155/1299 [01:21<00:03, 36.38it/s]

Error fetching O: Too Many Requests. Rate limited. Try after a while.
Error fetching D: Too Many Requests. Rate limited. Try after a while.
Error fetching BHF: Too Many Requests. Rate limited. Try after a while.
Error fetching KIM-PN: Too Many Requests. Rate limited. Try after a while.
Error fetching CTSH: Too Many Requests. Rate limited. Try after a while.
Error fetching KRUS: Too Many Requests. Rate limited. Try after a while.
Error fetching MAS: Too Many Requests. Rate limited. Try after a while.
Error fetching BANR: Too Many Requests. Rate limited. Try after a while.

sectors:  90%|████████▉ | 1163/1299 [01:21<00:03, 36.20it/s]

Error fetching CYTK: Too Many Requests. Rate limited. Try after a while.
Error fetching XYZ: Too Many Requests. Rate limited. Try after a while.
Error fetching CTBI: Too Many Requests. Rate limited. Try after a while.
Error fetching GAM: Too Many Requests. Rate limited. Try after a while.
Error fetching AVT: Too Many Requests. Rate limited. Try after a while.
Error fetching DLB: Too Many Requests. Rate limited. Try after a while.
Error fetching ESTA: Too Many Requests. Rate limited. Try after a while.
Error fetching CHEF: Too Many Requests. Rate limited. Try after a while.

sectors:  90%|█████████ | 1171/1299 [01:21<00:03, 36.70it/s]

Error fetching BHE: Too Many Requests. Rate limited. Try after a while.
Error fetching QVMT: Too Many Requests. Rate limited. Try after a while.
Error fetching RYAAY: Too Many Requests. Rate limited. Try after a while.
Error fetching FTDR: Too Many Requests. Rate limited. Try after a while.
Error fetching MPLX: Too Many Requests. Rate limited. Try after a while.
Error fetching BALL: Too Many Requests. Rate limited. Try after a while.
Error fetching IRON: Too Many Requests. Rate limited. Try after a while.
Error fetching FET: Too Many Requests. Rate limited. Try after a while.

sectors:  91%|█████████ | 1179/1299 [01:21<00:03, 36.45it/s]

Error fetching PSIX: Too Many Requests. Rate limited. Try after a while.
Error fetching CFG: Too Many Requests. Rate limited. Try after a while.
Error fetching TMHC: Too Many Requests. Rate limited. Try after a while.
Error fetching RRR: Too Many Requests. Rate limited. Try after a while.
Error fetching EMBJ: Too Many Requests. Rate limited. Try after a while.
Error fetching LOAR: Too Many Requests. Rate limited. Try after a while.
Error fetching FOUR-PA: Too Many Requests. Rate limited. Try after a while.
Error fetching CARR: Too Many Requests. Rate limited. Try after a while.

sectors:  91%|█████████▏| 1187/1299 [01:22<00:03, 36.81it/s]

Error fetching APO-PA: Too Many Requests. Rate limited. Try after a while.
Error fetching KGS: Too Many Requests. Rate limited. Try after a while.
Error fetching STC: Too Many Requests. Rate limited. Try after a while.
Error fetching TXNM: Too Many Requests. Rate limited. Try after a while.
Error fetching EQR: Too Many Requests. Rate limited. Try after a while.
Error fetching JOYY: Too Many Requests. Rate limited. Try after a while.
Error fetching ATKR: Too Many Requests. Rate limited. Try after a while.
Error fetching FAF: Too Many Requests. Rate limited. Try after a while.

sectors:  92%|█████████▏| 1195/1299 [01:22<00:02, 36.58it/s]

Error fetching ATMU: Too Many Requests. Rate limited. Try after a while.
Error fetching FR: Too Many Requests. Rate limited. Try after a while.
Error fetching MCHPP: Too Many Requests. Rate limited. Try after a while.
Error fetching PRLB: Too Many Requests. Rate limited. Try after a while.
Error fetching CSR: Too Many Requests. Rate limited. Try after a while.
Error fetching TFIN: Too Many Requests. Rate limited. Try after a while.
Error fetching CNXN: Too Many Requests. Rate limited. Try after a while.
Error fetching ASA: Too Many Requests. Rate limited. Try after a while.

sectors:  93%|█████████▎| 1203/1299 [01:22<00:02, 36.63it/s]

Error fetching PKX: Too Many Requests. Rate limited. Try after a while.
Error fetching BTI: Too Many Requests. Rate limited. Try after a while.
Error fetching ESNT: Too Many Requests. Rate limited. Try after a while.
Error fetching RLI: Too Many Requests. Rate limited. Try after a while.
Error fetching CCS: Too Many Requests. Rate limited. Try after a while.
Error fetching CBU: Too Many Requests. Rate limited. Try after a while.
Error fetching FOXA: Too Many Requests. Rate limited. Try after a while.
Error fetching GIL: Too Many Requests. Rate limited. Try after a while.

sectors:  93%|█████████▎| 1211/1299 [01:22<00:02, 36.63it/s]

Error fetching PARR: Too Many Requests. Rate limited. Try after a while.
Error fetching MDLZ: Too Many Requests. Rate limited. Try after a while.
Error fetching TS: Too Many Requests. Rate limited. Try after a while.
Error fetching BMY: Too Many Requests. Rate limited. Try after a while.
Error fetching MSGE: Too Many Requests. Rate limited. Try after a while.
Error fetching CAKE: Too Many Requests. Rate limited. Try after a while.
Error fetching OVV: Too Many Requests. Rate limited. Try after a while.
Error fetching PCOR: Too Many Requests. Rate limited. Try after a while.

sectors:  94%|█████████▍| 1219/1299 [01:23<00:02, 36.88it/s]

Error fetching RBLX: Too Many Requests. Rate limited. Try after a while.
Error fetching LKFN: Too Many Requests. Rate limited. Try after a while.
Error fetching ARWR: Too Many Requests. Rate limited. Try after a while.
Error fetching HAE: Too Many Requests. Rate limited. Try after a while.
Error fetching NXG: Too Many Requests. Rate limited. Try after a while.
Error fetching HTO: Too Many Requests. Rate limited. Try after a while.
Error fetching DAR: Too Many Requests. Rate limited. Try after a while.
Error fetching FISV: Too Many Requests. Rate limited. Try after a while.

sectors:  94%|█████████▍| 1227/1299 [01:23<00:01, 36.79it/s]

Error fetching ATLC: Too Many Requests. Rate limited. Try after a while.
Error fetching QXO-PB: Too Many Requests. Rate limited. Try after a while.
Error fetching SPSC: Too Many Requests. Rate limited. Try after a while.
Error fetching FHI: Too Many Requests. Rate limited. Try after a while.
Error fetching OKLO: Too Many Requests. Rate limited. Try after a while.
Error fetching NYAX: Too Many Requests. Rate limited. Try after a while.
Error fetching AA: Too Many Requests. Rate limited. Try after a while.
Error fetching PII: Too Many Requests. Rate limited. Try after a while.

sectors:  95%|█████████▌| 1235/1299 [01:23<00:01, 36.79it/s]

Error fetching NEE-PS: Too Many Requests. Rate limited. Try after a while.
Error fetching COLM: Too Many Requests. Rate limited. Try after a while.
Error fetching APEI: Too Many Requests. Rate limited. Try after a while.
Error fetching FTV: Too Many Requests. Rate limited. Try after a while.
Error fetching CTA-PA: Too Many Requests. Rate limited. Try after a while.
Error fetching AMRZ: Too Many Requests. Rate limited. Try after a while.
Error fetching BLBD: Too Many Requests. Rate limited. Try after a while.
Error fetching MNPR: Too Many Requests. Rate limited. Try after a while.

sectors:  96%|█████████▌| 1243/1299 [01:23<00:01, 37.02it/s]

Error fetching FTS: Too Many Requests. Rate limited. Try after a while.
Error fetching ZION: Too Many Requests. Rate limited. Try after a while.
Error fetching EDU: Too Many Requests. Rate limited. Try after a while.
Error fetching BWA: Too Many Requests. Rate limited. Try after a while.
Error fetching KNX: Too Many Requests. Rate limited. Try after a while.
Error fetching FCX: Too Many Requests. Rate limited. Try after a while.
Error fetching MAIN: Too Many Requests. Rate limited. Try after a while.
Error fetching CHMG: Too Many Requests. Rate limited. Try after a while.

sectors:  96%|█████████▋| 1251/1299 [01:23<00:01, 36.25it/s]

Error fetching BMRN: Too Many Requests. Rate limited. Try after a while.
Error fetching MGA: Too Many Requests. Rate limited. Try after a while.
Error fetching ESP: Too Many Requests. Rate limited. Try after a while.
Error fetching COCO: Too Many Requests. Rate limited. Try after a while.
Error fetching PCVX: Too Many Requests. Rate limited. Try after a while.
Error fetching AMBA: Too Many Requests. Rate limited. Try after a while.
Error fetching GLNG: Too Many Requests. Rate limited. Try after a while.
Error fetching SWKS: Too Many Requests. Rate limited. Try after a while.

sectors:  97%|█████████▋| 1259/1299 [01:24<00:01, 36.58it/s]

Error fetching XENE: Too Many Requests. Rate limited. Try after a while.
Error fetching DKL: Too Many Requests. Rate limited. Try after a while.
Error fetching MJSC: Too Many Requests. Rate limited. Try after a while.
Error fetching NJR: Too Many Requests. Rate limited. Try after a while.
Error fetching CRVL: Too Many Requests. Rate limited. Try after a while.
Error fetching EFSC: Too Many Requests. Rate limited. Try after a while.
Error fetching FBNC: Too Many Requests. Rate limited. Try after a while.
Error fetching ENB: Too Many Requests. Rate limited. Try after a while.

sectors:  98%|█████████▊| 1267/1299 [01:24<00:00, 37.07it/s]

Error fetching MC: Too Many Requests. Rate limited. Try after a while.
Error fetching NOVTU: Too Many Requests. Rate limited. Try after a while.
Error fetching LVS: Too Many Requests. Rate limited. Try after a while.
Error fetching MEOH: Too Many Requests. Rate limited. Try after a while.
Error fetching WHR: Too Many Requests. Rate limited. Try after a while.
Error fetching PAHC: Too Many Requests. Rate limited. Try after a while.
Error fetching TBBK: Too Many Requests. Rate limited. Try after a while.
Error fetching FBIZ: Too Many Requests. Rate limited. Try after a while.

sectors:  98%|█████████▊| 1275/1299 [01:24<00:00, 37.34it/s]

Error fetching YOU: Too Many Requests. Rate limited. Try after a while.
Error fetching NKE: Too Many Requests. Rate limited. Try after a while.
Error fetching SFST: Too Many Requests. Rate limited. Try after a while.
Error fetching CALX: Too Many Requests. Rate limited. Try after a while.
Error fetching PFIS: Too Many Requests. Rate limited. Try after a while.
Error fetching EMO: Too Many Requests. Rate limited. Try after a while.
Error fetching MP: Too Many Requests. Rate limited. Try after a while.
Error fetching ROL: Too Many Requests. Rate limited. Try after a while.

sectors:  99%|█████████▉| 1283/1299 [01:24<00:00, 37.04it/s]

Error fetching HUT: Too Many Requests. Rate limited. Try after a while.
Error fetching LGN: Too Many Requests. Rate limited. Try after a while.
Error fetching SPG-PJ: Too Many Requests. Rate limited. Try after a while.
Error fetching GSK: Too Many Requests. Rate limited. Try after a while.
Error fetching KBH: Too Many Requests. Rate limited. Try after a while.
Error fetching BXP: Too Many Requests. Rate limited. Try after a while.
Error fetching ESTC: Too Many Requests. Rate limited. Try after a while.
Error fetching MAA-PI: Too Many Requests. Rate limited. Try after a while.

sectors:  99%|█████████▉| 1291/1299 [01:25<00:00, 36.70it/s]

Error fetching BROS: Too Many Requests. Rate limited. Try after a while.
Error fetching ASO: Too Many Requests. Rate limited. Try after a while.
Error fetching OMF: Too Many Requests. Rate limited. Try after a while.
Error fetching SYM: Too Many Requests. Rate limited. Try after a while.
Error fetching NC: Too Many Requests. Rate limited. Try after a while.
Error fetching IIPR: Too Many Requests. Rate limited. Try after a while.
Error fetching OZ: Too Many Requests. Rate limited. Try after a while.
Error fetching ASTE: Too Many Requests. Rate limited. Try after a while.

sectors: 100%|██████████| 1299/1299 [01:25<00:00, 15.24it/s]

Error fetching TECH: Too Many Requests. Rate limited. Try after a while.
Error fetching E: Too Many Requests. Rate limited. Try after a while.
Error fetching FND: Too Many Requests. Rate limited. Try after a while.
Error fetching MT: Too Many Requests. Rate limited. Try after a while.
Error fetching NWN: Too Many Requests. Rate limited. Try after a while.
Error fetching MKC-V: Too Many Requests. Rate limited. Try after a while.
Error fetching FBK: Too Many Requests. Rate limited. Try after a while.
Error fetching GBX: Too Many Requests. Rate limited. Try after a while.

In [ ]:
# Inspecting for section with complete data
sector_industry_yf[0:933]

    symbol              sector                  industry
0    BRK-A  Financial Services   Insurance - Diversified
1      NVR   Consumer Cyclical  Residential Construction
2      SEB         Industrials             Conglomerates
3     BKNG   Consumer Cyclical           Travel Services
4      AZO   Consumer Cyclical                Auto Parts
..     ...                 ...                       ...
928    BFH  Financial Services           Credit Services
929   MRCY         Industrials       Aerospace & Defense
930    SBR              Energy       Oil & Gas Midstream
931   HSIC                None                      None
932    AIG                None                      None

[933 rows x 3 columns]

In [ ]:
# Saving data
# sector_industry_yf.to_csv("sector_industry_yf.csv", index=False)

## API Data Access - Instagram

### Data Extraction Function

In [ ]:
import requests
import pandas as pd
import time

def fetch_hashtag(hashtag, access_token, user_id, limit=50, sleep_time=1):

    print(f"Fetching data for #{hashtag}")

    # Getting hashtag ID
    search_url = "https://graph.facebook.com/v18.0/ig_hashtag_search"
    params = {
        "user_id": user_id,
        "q": hashtag,
        "access_token": access_token
    }

    response = requests.get(search_url, params=params).json()

    if "data" not in response or len(response["data"]) == 0:
        raise Exception(f"Error fetching hashtag ID: {response}")

    hashtag_id = response["data"][0]["id"]
    print(f"Hashtag ID: {hashtag_id}")

    # Getting Data
    media_url = f"https://graph.facebook.com/v18.0/{hashtag_id}/recent_media"
    params = {
        "user_id": user_id,
        "fields": "id,media_type,timestamp,like_count,comments_count",
        "access_token": access_token,
        "limit": limit
    }

    all_posts = []

    while True:
        response = requests.get(media_url, params=params).json()

        if "error" in response:
            print("Error:", response["error"])
            break

        data = response.get("data", [])

        for post in data:
            post["hashtag"] = f"#{hashtag}"

        all_posts.extend(data)

        print(f"Collected: {len(all_posts)} posts")

        # Pagination
        paging = response.get("paging", {})
        next_page = paging.get("next")

        if not next_page:
            print("No more pages.")
            break

        media_url = next_page
        params = None

        time.sleep(sleep_time)

    return pd.DataFrame(all_posts)

### API Details

In [ ]:
# Setting up Token and User ID
ACCESS_TOKEN = "EAAWtfIhRNW4BRDdq955EJECLZAiRKswEuDRxbCW4aRnnIbPONZAPKyxZAxUd9FFQtsZAEZC89Jx79f4h723g5ZBZBfQmPZAmrNUfyzdvhXXO3ljxZBHatruHNvqLym2wsonPUQlEnJCIAJRZAT5NeRy5d7ZBIFHZBiEcQCv9CHdsKDYSIZCTZARpy3PamgG0UX7V5dALpjlWes0C310V8e4EWPP80tqmgIY8qnKrKTyKygPBh1X6GOG45QwLgbwqGVFXIZBZBhpz0yQjNZBPghZBkZD"
USER_ID = "17841438742949128"

### Data Extraction

In [ ]:
# AppleEvent2025
df_apple = fetch_hashtag("AppleEvent2025", ACCESS_TOKEN, USER_ID)
df_apple.to_csv("df_apple.csv")

In [ ]:
# MadeByGoogle
df_google = fetch_hashtag("MadeByGoogle", ACCESS_TOKEN, USER_ID)
df_google.to_csv("df_google.csv")

In [ ]:
# GalaxyS25
df_s25 = fetch_hashtag("#GalaxyS25", ACCESS_TOKEN, USER_ID)
df_s25.to_csv("df_s25.csv")

In [ ]:
# GalaxyS25Edge
df_s25_edge = fetch_hashtag("#GalaxyS25Edge", ACCESS_TOKEN, USER_ID)
df_s25_edge.to_csv("df_s25_edge.csv")